server:
  port: 8082

spring:
  kafka:
    topic:
      name: tweets
    consumer:
      bootstrap-servers: localhost:9092
      group-id: twitter
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

producer:
  host: http://localhost:8081
  relativePath: /coopX/v1/streamTweets/produceDataStream?ruleFilter=